---
- name: remove suid/guid binaries from blacklist
  file:
    path: "{{ item }}"
    mode: a-s
    state: file
    follow: yes
  failed_when: false
  with_flattened:
    - "{{ os_suid_guid_blacklist }}"

- name: finding all binaries set with suid/sgid bit
  shell: find / -xdev \( -perm -4000 -o -perm -2000 \) -type f ! -path '/proc/*' -print 2>/dev/null
  register: sbit_binaries
  when: os_suid_sgid_remove_from_unknown | bool
  changed_when: false


- name: gather files so as to remove suid/guid from whitelisted files
  set_fact:
    suid: "{{ sbit_binaries.stdout_lines | difference(os_suid_sgid_whitelist) }}"
  when: os_suid_sgid_remove_from_unknown | bool

- name: remove suid/sgid from all binaries except whitelist
  file:
    path: "{{ item }}"
    mode: a-s
    state: file
    follow: yes
  with_flattened: 
    - "{{ suid | default([]) | difference(os_suid_sgid_whitelist) }}"
  when: os_suid_sgid_remove_from_unknown | bool
